// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechNova.Data;

#nullable disable

namespace TechNova.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechNova.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("TechNova.Models.Founder", b =>
                {
                    b.Property<int>("FounderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FounderID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartupID")
                        .HasColumnType("int");

                    b.HasKey("FounderID");

                    b.HasIndex("StartupID");

                    b.ToTable("Founders");
                });

            modelBuilder.Entity("TechNova.Models.InvestmentRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestID"));

                    b.Property<decimal>("InvestmentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvestorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartupID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestID");

                    b.HasIndex("InvestorID");

                    b.HasIndex("StartupID");

                    b.ToTable("InvestmentRequests");
                });

            modelBuilder.Entity("TechNova.Models.Investor", b =>
                {
                    b.Property<int>("InvestorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestorID"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("InvestmentRange")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Preference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VerifiedByAdminID")
                        .HasColumnType("int");

                    b.HasKey("InvestorID");

                    b.HasIndex("VerifiedByAdminID");

                    b.ToTable("Investors");
                });

            modelBuilder.Entity("TechNova.Models.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvestorID")
                        .HasColumnType("int");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartupID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageID");

                    b.HasIndex("InvestorID");

                    b.HasIndex("StartupID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TechNova.Models.PitchDeck", b =>
                {
                    b.Property<int>("PitchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PitchID"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartupID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PitchID");

                    b.HasIndex("StartupID");

                    b.ToTable("PitchDecks");
                });

            modelBuilder.Entity("TechNova.Models.Startup", b =>
                {
                    b.Property<int>("StartupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StartupID"));

                    b.Property<string>("BusinessStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FundingRequired")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VerifiedByAdminID")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StartupID");

                    b.HasIndex("VerifiedByAdminID");

                    b.ToTable("Startups");
                });

            modelBuilder.Entity("TechNova.Models.Founder", b =>
                {
                    b.HasOne("TechNova.Models.Startup", "Startup")
                        .WithMany("Founders")
                        .HasForeignKey("StartupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("TechNova.Models.InvestmentRequest", b =>
                {
                    b.HasOne("TechNova.Models.Investor", "Investor")
                        .WithMany("InvestmentRequests")
                        .HasForeignKey("InvestorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechNova.Models.Startup", "Startup")
                        .WithMany("InvestmentRequests")
                        .HasForeignKey("StartupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("TechNova.Models.Investor", b =>
                {
                    b.HasOne("TechNova.Models.Admin", "VerifiedByAdmin")
                        .WithMany("VerifiedInvestors")
                        .HasForeignKey("VerifiedByAdminID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VerifiedByAdmin");
                });

            modelBuilder.Entity("TechNova.Models.Message", b =>
                {
                    b.HasOne("TechNova.Models.Investor", "Investor")
                        .WithMany("Messages")
                        .HasForeignKey("InvestorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechNova.Models.Startup", "Startup")
                        .WithMany("Messages")
                        .HasForeignKey("StartupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("TechNova.Models.PitchDeck", b =>
                {
                    b.HasOne("TechNova.Models.Startup", "Startup")
                        .WithMany("PitchDecks")
                        .HasForeignKey("StartupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("TechNova.Models.Startup", b =>
                {
                    b.HasOne("TechNova.Models.Admin", "VerifiedByAdmin")
                        .WithMany("VerifiedStartups")
                        .HasForeignKey("VerifiedByAdminID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VerifiedByAdmin");
                });

            modelBuilder.Entity("TechNova.Models.Admin", b =>
                {
                    b.Navigation("VerifiedInvestors");

                    b.Navigation("VerifiedStartups");
                });

            modelBuilder.Entity("TechNova.Models.Investor", b =>
                {
                    b.Navigation("InvestmentRequests");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TechNova.Models.Startup", b =>
                {
                    b.Navigation("Founders");

                    b.Navigation("InvestmentRequests");

                    b.Navigation("Messages");

                    b.Navigation("PitchDecks");
                });
#pragma warning restore 612, 618
        }
    }
}
